version: "3.7"

services:
  cockroach:
    image: docker.uclv.cu/cockroachdb/cockroach:latest-v21.2
    container_name: cockroach
    volumes:
      - cockroach:/cockroach/cockroach-data
    ports:
      - 26222:26257
      - 8888:8080
    restart: always
    command: start-single-node --insecure
  redis:
    image: docker.uclv.cu/redis:alpine
    container_name: redis
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb:0.11.9
    ports: 
      - "8085:8081" 
    links: 
      - cockroach:cockroach 
    environment:
      - DATABASE_URL=postgres://root:root@cockroach:26257/postgres?sslmode=disable
    depends_on:
      - cockroach
  # gendocu:
  #   container_name: gendocu
  #   restart: always
  #   image: docker.uclv.cu/gendocu/grpc-docs
  #   ports: 
  #     - "8085:8080" 
  #   volumes:
  #     - ./proto:/input
  #     - gendocu:/output
  # db:
  #   image: docker.uclv.cu/postgis/postgis:13-3.1-alpine 
  #   container_name: ownpostgis
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   restart: always
  #   environment:
  #     POSTGRES_HOST_AUTH_METHOD: scram-sha-256
  #     POSTGRES_DB: postgres
  #     POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 --auth-local=scram-sha-256
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  # pgadmin4:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4
  #   volumes:
  #     - pgadmin4:/var/lib/pgadmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.net
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - 8080:80
  # minio:
  #   image: docker.uclv.cu/minio/minio:RELEASE.2022-01-08T03-11-54Z
  #   container_name: minio
  #   volumes:
  #     - miniodata:/data
  #   restart: always
  #   command: server /data --console-address ":9001"
  #   environment:
  #     MINIO_ROOT_USER: root
  #     MINIO_ROOT_PASSWORD: root1234
  #   ports:
  #     - 9011:9000
  #     - 9010:9001
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  createbuckets:
    image: docker.uclv.cu/minio/mc:RELEASE.2022-04-16T21-11-21Z
    depends_on:
      minio:
        condition: service_healthy
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://192.168.0.2:9011 root root1234;
      /usr/bin/mc mb minio/business-avatar;
      /usr/bin/mc mb minio/business-avatar-deleted;
      /usr/bin/mc mb minio/items;
      /usr/bin/mc mb minio/items-deleted;
      /usr/bin/mc mb minio/user-avatar;
      /usr/bin/mc mb minio/users-deleted;
      /usr/bin/mc policy set public minio/business-avatar;
      /usr/bin/mc policy set public minio/business-avatar-deleted;
      /usr/bin/mc policy set public minio/items;
      /usr/bin/mc policy set public minio/items-deleted;
      /usr/bin/mc policy set public minio/user-avatar;
      /usr/bin/mc policy set public minio/users-deleted;
      "
volumes:
  cockroach:
  # miniodata:
  pgadmin4:
