version: "3.7"

services:
  api:
    image: danielarmasjuarez/api:v0.30.0
    container_name: api
    ports:
      - 22210:22210
    restart: always
    environment:
      DB_USER: root               
      DB_PASSWORD: root            
      DB_DATABASE: postgres
      DB_PORT: 26257             
      DB_HOST: cockroach               
      API_PORT: 22210
      PROMETHEUS_PUSHGATEWAY: http://localhost:9091/
      JWT_SECRET: O8pzXjp4QMk4cAD60dHeoOnxdVsDc9
      BUSINESS_AVATAR_BULK_NAME: business-avatar
      ITEMS_BULK_NAME: items
      ITEMS_DELETED_BULK_NAME: items-deleted
      USERS_BULK_NAME: user-avatar
      USERS_DELETED_BULK_NAME: users-deleted
      OBJECT_STORAGE_SERVER_USE_SSL: "false"
      OBJECT_STORAGE_SERVER_ACCESS_KEY_ID: root
      OBJECT_STORAGE_SERVER_SECRET_ACCESS_KEY: root1234
      OBJECT_STORAGE_SERVER_ENDPOINT: minio:9000
    depends_on:
      - cockroach
  cockroach:
    image: docker.uclv.cu/cockroachdb/cockroach:latest-v21.2
    container_name: cockroach
    volumes:
      - cockroach:/cockroach/cockroach-data
    ports:
      - 26257:26257
      - 8082:8080
    restart: always
    command: start-single-node --insecure
  pgweb:
    container_name: pgweb
    restart: always
    image: docker.uclv.cu/sosedoff/pgweb:0.11.9
    ports: 
      - "8083:8081" 
    links: 
      - cockroach:cockroach 
    environment:
      - DATABASE_URL=postgres://root:root@cockroach:26257/postgres?sslmode=disable
    depends_on:
      - cockroach
  minio:
    image: docker.uclv.cu/minio/minio:RELEASE.2021-10-23T03-28-24Z
    container_name: minio
    volumes:
      - miniodata:/data
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root1234
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   volumes:
  #     - pgadmin4:/var/lib/pgadmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.net
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - 8080:80
volumes:
  cockroach:
  miniodata:
  # pgadmin4:
