apiVersion: skaffold/v2beta19
kind: Config
build:
  artifacts:
  - image: cr.lanave/amorgant/server-debug
    buildpacks:
      builder: cr.lanave.io/buildpacks/builder:v1
    context: .
    sync: 
      auto: true 
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yml