name: Docker Image CI

on:
  release:
    types: [published]
  # push:
  #   branches: [main, develop]
  # pull_request:
  #   branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag danielarmasjuarez/api:$(git describe --abbrev=0 --tags)
